name: Build and Run Tests

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          apt update -y && apt install -y python3 python3-pip curl wget
          pip install -r requirements.txt

      - name: Run tests
        run: python3 app.py
